- project:
    templates:
      - nodejs14-jobs
    check:
      jobs:
        - nodejs-run-docs:
            vars:
              node_version: 14
            nodeset: ubuntu-focal
    gate:
      jobs:
        - nodejs-run-docs:
            vars:
              node_version: 14
            nodeset: ubuntu-focal
